name: deformetrica
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - python=3.7
  - numpy=1.16.2
  - scikit-learn=0.20.3
  - matplotlib=2.2.2
  - nibabel=2.3.3
  - pillow=5.1.0
  - h5py=2.9.0  # fix: h5py conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated
  - pytorch=1.0.1
  - cudatoolkit=8.0
  - pyqt=5.9
  - vtk=8.2.0
  - psutil=5.4.8
  - pip
  - pip:
    - gputil==1.3.0
    - pykeops==1.0.1
    - cmake>=3.10
    - scikit-learn
